import { Schema } from "effect";

/**
 * Shared validation constants
 */
export const TASK_MAX_LENGTH = 50000;

/**
 * Valid run status values
 * - started: Task accepted, sandbox spinning up
 * - running: OpenCode is actively working
 * - completed: Finished successfully
 * - failed: Finished with error
 */
export const RunStatus = Schema.Literal("started", "running", "completed", "failed");
export type RunStatus = typeof RunStatus.Type;

/**
 * Result of a completed run - simplified to unstructured output
 */
export const RunResult = Schema.Struct({
  success: Schema.Boolean,
  output: Schema.String,
  error: Schema.optionalWith(Schema.String, { exact: true }),
});
export type RunResult = typeof RunResult.Type;

/**
 * Status of an individual workflow step
 */
export const StepStatus = Schema.Literal("pending", "running", "completed", "failed");
export type StepStatus = typeof StepStatus.Type;

/**
 * Detailed information about a run phase/step
 */
export const RunPhase = Schema.Struct({
  status: StepStatus,
  durationMs: Schema.optionalWith(Schema.Number, { exact: true }),
  error: Schema.optionalWith(Schema.String, { exact: true }),
});
export type RunPhase = typeof RunPhase.Type;

/**
 * Complete run record stored in R2
 */
export const RunRecord = Schema.Struct({
  runId: Schema.String,
  sessionId: Schema.String,
  workflowId: Schema.String,
  status: RunStatus,
  task: Schema.String,
  title: Schema.String, // Short label (provided or auto-generated by OpenCode)
  model: Schema.String,
  startedAt: Schema.Number,
  completedAt: Schema.optionalWith(Schema.Number, { exact: true }),
  result: Schema.optionalWith(RunResult, { exact: true }),
  currentStep: Schema.optionalWith(Schema.String, { exact: true }),
  phases: Schema.optionalWith(Schema.Record({ key: Schema.String, value: RunPhase }), { exact: true }),
});
export type RunRecord = typeof RunRecord.Type;
